### ISSUE TITLE
Pycuda error during Tensorrt inference

### ISSUE THREAD

**Issue by PankajJ08** [Star-Clouds/CenterFace#71]
I converted onnx model into trt file on jetson nano using tensorrt 5, cuda 10, python 3.6...
But I'm getting the error related to pycuda.
Traceback is:
File "demo.py", line 30, in <module>
    test_image_tensorrt()
  File "demo.py", line 13, in test_image_tensorrt
    dets, lms = centerface(frame, h, w, threshold=0.35)
  File "/ML/CenterFace/prj-tensorrt/centerface.py", line 21, in __call__
    return self.inference_tensorrt(img, threshold)
  File "/ML/CenterFace/prj-tensorrt/centerface.py", line 91, in inference_tensorrt
    trt_outputs = do_inference(context, bindings=bindings, inputs=inputs, outputs=outputs, stream=stream)  # numpy data
  File "/ML/CenterFace/prj-tensorrt/centerface.py", line 60, in do_inference
    [cuda.memcpy_htod_async(inp.device, inp.host, stream) for inp in inputs]
  File "/ML/CenterFace/prj-tensorrt/centerface.py", line 60, in <listcomp>
    [cuda.memcpy_htod_async(inp.device, inp.host, stream) for inp in inputs]
pycuda._driver.LogicError: cuMemcpyHtoDAsync failed: invalid argument

**Comment by ywlife** [comment]
Maybe you can try tensorrt 7.

**Comment by PankajJ08** [comment]
I have found the reason for the error. it's due the size of the input of onnx model, it must be 32 * 32. On any other input, error occured.

**Comment by PankajJ08** [comment]
I have found the reason for the error. it's due the size of the input of onnx model, it must be 32 * 32. On any other input, an error occured.

**Comment by nsabir2011** [comment]
@PankajJ08 
Hi,
Could you please give me some pointers on how you fixed the problem? I am having the same issue. But don't know how to change the input size of the onnx model to 32 * 32.

**Comment by xxxpsyduck** [comment]
@PankajJ08 Can you give more detail?
